cfg = {
    "project_root": "/home/tus/Desktop/wyl/MambaHash",
    "dataset": "mirflickr25k",  # mirflickr25k nuswide coco icpatc
    "device": 0,
    "train_batch_size": 100,
    "query_batch_size": 100,
    "retrieval_batch_size": 100,
    "train_epoch": 20,
    "dropout": 0.25,
    "num_workers": 4,
    "num_bit": 64,
    "num_query": 5000,
    "num_train": 10000,
    "clip_lr": 0.00001,
    "other_lr": 0.001,
    "image_resolution": 224,  # 256
    "seed": 1814,
    "out_dim": 512,  # 512
    "max_words": 77,  # 64
    "list_bit": [16, 32, 64],
    "name_clip": "/home/tus/Desktop/wyl/ViT-B-32.pt",
    "model_name": "hf-hub:timm/ViT-B-16-SigLIP2-256",
    "index_file": "index.mat",
    "caption_file": "caption.mat",
    "label_file": "label.mat",
}

cfg["flickr25k_class_name_list"] = [
    "animals",
    "baby",
    "bird",
    "car",
    "clouds",
    "dog",
    "female",
    "flower",
    "food",
    "indoor",
    "lake",
    "male",
    "night",
    "people",
    "plant_life",
    "portrait",
    "river",
    "sea",
    "sky",
    "structures",
    "sunset",
    "transport",
    "tree",
    "water",
]
cfg["nuswide_class_name_list"] = [
    "animal",
    "beach",
    "buildings",
    "clouds",
    "flowers",
    "grass",
    "lake",
    "mountain",
    "ocean",
    "person",
    "plants",
    "reflection",
    "road",
    "rocks",
    "sky",
    "snow",
    "sunset",
    "tree",
    "vehicle",
    "water",
    "window",
]
cfg["coco_class_name_list"] = [
    "person",
    "bicycle",
    "car",
    "motorbike",
    "aeroplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "sofa",
    "pottedplant",
    "bed",
    "diningtable",
    "toilet",
    "tvmonitor",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

if cfg["dataset"] == "mirflickr25k":
    cfg["num_class"] = 24
    cfg["class_name_list"] = cfg["flickr25k_class_name_list"]
elif cfg["dataset"] == "nuswide":
    cfg["num_class"] = 21
    cfg["caption_file"] = "caption.txt"
    cfg["class_name_list"] = cfg["nuswide_class_name_list"]
elif cfg["dataset"] == "coco":
    cfg["num_class"] = 80
    cfg["class_name_list"] = cfg["coco_class_name_list"]
